server:
  port: 8080
spring:
  application:
    name: videoStoreExam

  data:
    jpa:
      repositories:
        # 'bootstrap-mode' valori ammessi:
        #   - DEFAULT -> I repositories vengono inizializzati all'avvio dell'applicazione
        #   - DEFERRED -> I repositories vengono inizializzati all'avvio dell'applicazione ma in modo asincrono
        #   - LAZY -> I repositories vengono inizializzati nel momento in cui vengono richiamati (velocizza l'avvio dell'applicazione ma aumenta i tempi di latenza alla prima chiamata)
        bootstrap-mode: DEFAULT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6603/video_store_exam?createDatabaseIfNotExist=true&autoReconnect=true&useSLL=false&useLegacyDatetimeCode=false
    username: administrator
    password: mysqlDocker
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        '[format_sql]': true
        jdbc:
        '[time_zone]': Europe/Rome
        generate_statistics: false
    show-sql: true
  sql:
    init:
      # Qualora nel package resources ci sia un file data.sql, le istruzioni ivi contenute potrebbero essere eseguite
      # 'mode' valori ammessi:
      #  - never -> non vengono mai eseguite le istruzioni presenti nel file data.sql
      #  - always -> vengono sempre eseguite le istruzioni presenti nel file data.sql. N.B. Se la propiet? spring.jpa.defer-datasource-initialization ? a false, le istruzioni vengono eseguite istantaneamente; se impostato a true, le istruzioni sql vengono eseguite dopo l'avvio dell'applicazione (ovvero in maniera differita)
      #  - embedded -> vengono sempre eseguite le istruzioni presenti nel file data.sql a patto che il database sia di tipo embedded (es. H2, Derby, etc...)
      mode: never

  jackson:
    serialization:
      indent-output: true

logging:
  level:
    it:
      test:
        solution: info
    org:
      springframework: info
      hibernate:
        stat: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace